//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}Description"/>
 *         &lt;element name="LeadCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Years">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Year" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Open" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Close" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Periods" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Period" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
 *                             &lt;element name="Groups" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Group" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element ref="{}Journal" minOccurs="0"/>
 *                                                 &lt;element ref="{}Costcenter" minOccurs="0"/>
 *                                                 &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ReportingYear" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}code"/>
 *       &lt;attribute ref="{}balanceType"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "leadCode",
    "years"
})
@XmlRootElement(name = "Balance")
public class Balance {

    @XmlElement(name = "Description")
    protected TypeDescription description;
    @XmlElement(name = "LeadCode")
    protected String leadCode;
    @XmlElement(name = "Years")
    protected Balance.Years years;
    @XmlAttribute
    protected String code;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String balanceType;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setDescription(TypeDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the leadCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadCode() {
        return leadCode;
    }

    /**
     * Sets the value of the leadCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadCode(String value) {
        this.leadCode = value;
    }

    /**
     * Gets the value of the years property.
     * 
     * @return
     *     possible object is
     *     {@link Balance.Years }
     *     
     */
    public Balance.Years getYears() {
        return years;
    }

    /**
     * Sets the value of the years property.
     * 
     * @param value
     *     allowed object is
     *     {@link Balance.Years }
     *     
     */
    public void setYears(Balance.Years value) {
        this.years = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the balanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * Sets the value of the balanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceType(String value) {
        this.balanceType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Year" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Open" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Close" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Periods" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Period" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
     *                   &lt;element name="Groups" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Group" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element ref="{}Journal" minOccurs="0"/>
     *                                       &lt;element ref="{}Costcenter" minOccurs="0"/>
     *                                       &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ReportingYear" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "year"
    })
    public static class Years {

        @XmlElement(name = "Year", required = true)
        protected List<Balance.Years.Year> year;

        /**
         * Gets the value of the year property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the year property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getYear().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Balance.Years.Year }
         * 
         * 
         */
        public List<Balance.Years.Year> getYear() {
            if (year == null) {
                year = new ArrayList<Balance.Years.Year>();
            }
            return this.year;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Open" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Close" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Periods" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Period" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
         *         &lt;element name="Groups" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Group" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element ref="{}Journal" minOccurs="0"/>
         *                             &lt;element ref="{}Costcenter" minOccurs="0"/>
         *                             &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ReportingYear" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "open",
            "debit",
            "credit",
            "close",
            "periods",
            "costAnalysis",
            "groups"
        })
        public static class Year {

            @XmlElement(name = "Open")
            protected float open;
            @XmlElement(name = "Debit")
            protected float debit;
            @XmlElement(name = "Credit")
            protected float credit;
            @XmlElement(name = "Close")
            protected float close;
            @XmlElement(name = "Periods")
            protected Balance.Years.Year.Periods periods;
            @XmlElement(name = "CostAnalysis")
            protected BalanceCostAnalysisType costAnalysis;
            @XmlElement(name = "Groups")
            protected Balance.Years.Year.Groups groups;
            @XmlAttribute(name = "ReportingYear")
            protected BigInteger reportingYear;

            /**
             * Gets the value of the open property.
             * 
             */
            public float getOpen() {
                return open;
            }

            /**
             * Sets the value of the open property.
             * 
             */
            public void setOpen(float value) {
                this.open = value;
            }

            /**
             * Gets the value of the debit property.
             * 
             */
            public float getDebit() {
                return debit;
            }

            /**
             * Sets the value of the debit property.
             * 
             */
            public void setDebit(float value) {
                this.debit = value;
            }

            /**
             * Gets the value of the credit property.
             * 
             */
            public float getCredit() {
                return credit;
            }

            /**
             * Sets the value of the credit property.
             * 
             */
            public void setCredit(float value) {
                this.credit = value;
            }

            /**
             * Gets the value of the close property.
             * 
             */
            public float getClose() {
                return close;
            }

            /**
             * Sets the value of the close property.
             * 
             */
            public void setClose(float value) {
                this.close = value;
            }

            /**
             * Gets the value of the periods property.
             * 
             * @return
             *     possible object is
             *     {@link Balance.Years.Year.Periods }
             *     
             */
            public Balance.Years.Year.Periods getPeriods() {
                return periods;
            }

            /**
             * Sets the value of the periods property.
             * 
             * @param value
             *     allowed object is
             *     {@link Balance.Years.Year.Periods }
             *     
             */
            public void setPeriods(Balance.Years.Year.Periods value) {
                this.periods = value;
            }

            /**
             * Gets the value of the costAnalysis property.
             * 
             * @return
             *     possible object is
             *     {@link BalanceCostAnalysisType }
             *     
             */
            public BalanceCostAnalysisType getCostAnalysis() {
                return costAnalysis;
            }

            /**
             * Sets the value of the costAnalysis property.
             * 
             * @param value
             *     allowed object is
             *     {@link BalanceCostAnalysisType }
             *     
             */
            public void setCostAnalysis(BalanceCostAnalysisType value) {
                this.costAnalysis = value;
            }

            /**
             * Gets the value of the groups property.
             * 
             * @return
             *     possible object is
             *     {@link Balance.Years.Year.Groups }
             *     
             */
            public Balance.Years.Year.Groups getGroups() {
                return groups;
            }

            /**
             * Sets the value of the groups property.
             * 
             * @param value
             *     allowed object is
             *     {@link Balance.Years.Year.Groups }
             *     
             */
            public void setGroups(Balance.Years.Year.Groups value) {
                this.groups = value;
            }

            /**
             * Gets the value of the reportingYear property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getReportingYear() {
                return reportingYear;
            }

            /**
             * Sets the value of the reportingYear property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setReportingYear(BigInteger value) {
                this.reportingYear = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Group" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{}Journal" minOccurs="0"/>
             *                   &lt;element ref="{}Costcenter" minOccurs="0"/>
             *                   &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "group"
            })
            public static class Groups {

                @XmlElement(name = "Group", required = true)
                protected List<Balance.Years.Year.Groups.Group> group;

                /**
                 * Gets the value of the group property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the group property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getGroup().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Balance.Years.Year.Groups.Group }
                 * 
                 * 
                 */
                public List<Balance.Years.Year.Groups.Group> getGroup() {
                    if (group == null) {
                        group = new ArrayList<Balance.Years.Year.Groups.Group>();
                    }
                    return this.group;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{}Journal" minOccurs="0"/>
                 *         &lt;element ref="{}Costcenter" minOccurs="0"/>
                 *         &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "journal",
                    "costcenter",
                    "debit",
                    "credit"
                })
                public static class Group {

                    @XmlElement(name = "Journal")
                    protected Journal journal;
                    @XmlElement(name = "Costcenter")
                    protected Costcenter costcenter;
                    @XmlElement(name = "Debit")
                    protected float debit;
                    @XmlElement(name = "Credit")
                    protected float credit;

                    /**
                     * Gets the value of the journal property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Journal }
                     *     
                     */
                    public Journal getJournal() {
                        return journal;
                    }

                    /**
                     * Sets the value of the journal property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Journal }
                     *     
                     */
                    public void setJournal(Journal value) {
                        this.journal = value;
                    }

                    /**
                     * Gets the value of the costcenter property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Costcenter }
                     *     
                     */
                    public Costcenter getCostcenter() {
                        return costcenter;
                    }

                    /**
                     * Sets the value of the costcenter property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Costcenter }
                     *     
                     */
                    public void setCostcenter(Costcenter value) {
                        this.costcenter = value;
                    }

                    /**
                     * Gets the value of the debit property.
                     * 
                     */
                    public float getDebit() {
                        return debit;
                    }

                    /**
                     * Sets the value of the debit property.
                     * 
                     */
                    public void setDebit(float value) {
                        this.debit = value;
                    }

                    /**
                     * Gets the value of the credit property.
                     * 
                     */
                    public float getCredit() {
                        return credit;
                    }

                    /**
                     * Sets the value of the credit property.
                     * 
                     */
                    public void setCredit(float value) {
                        this.credit = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Period" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "period"
            })
            public static class Periods {

                @XmlElement(name = "Period", required = true)
                protected List<Balance.Years.Year.Periods.Period> period;

                /**
                 * Gets the value of the period property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the period property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPeriod().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Balance.Years.Year.Periods.Period }
                 * 
                 * 
                 */
                public List<Balance.Years.Year.Periods.Period> getPeriod() {
                    if (period == null) {
                        period = new ArrayList<Balance.Years.Year.Periods.Period>();
                    }
                    return this.period;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Debit" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="Credit" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="CostAnalysis" type="{}BalanceCostAnalysisType" minOccurs="0"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="ReportingPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "debit",
                    "credit",
                    "costAnalysis"
                })
                public static class Period {

                    @XmlElement(name = "Debit")
                    protected float debit;
                    @XmlElement(name = "Credit")
                    protected float credit;
                    @XmlElement(name = "CostAnalysis")
                    protected BalanceCostAnalysisType costAnalysis;
                    @XmlAttribute(name = "ReportingPeriod")
                    protected BigInteger reportingPeriod;

                    /**
                     * Gets the value of the debit property.
                     * 
                     */
                    public float getDebit() {
                        return debit;
                    }

                    /**
                     * Sets the value of the debit property.
                     * 
                     */
                    public void setDebit(float value) {
                        this.debit = value;
                    }

                    /**
                     * Gets the value of the credit property.
                     * 
                     */
                    public float getCredit() {
                        return credit;
                    }

                    /**
                     * Sets the value of the credit property.
                     * 
                     */
                    public void setCredit(float value) {
                        this.credit = value;
                    }

                    /**
                     * Gets the value of the costAnalysis property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BalanceCostAnalysisType }
                     *     
                     */
                    public BalanceCostAnalysisType getCostAnalysis() {
                        return costAnalysis;
                    }

                    /**
                     * Sets the value of the costAnalysis property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BalanceCostAnalysisType }
                     *     
                     */
                    public void setCostAnalysis(BalanceCostAnalysisType value) {
                        this.costAnalysis = value;
                    }

                    /**
                     * Gets the value of the reportingPeriod property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getReportingPeriod() {
                        return reportingPeriod;
                    }

                    /**
                     * Sets the value of the reportingPeriod property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setReportingPeriod(BigInteger value) {
                        this.reportingPeriod = value;
                    }

                }

            }

        }

    }

}
