//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Item"/>
 *         &lt;element ref="{}Description" minOccurs="0"/>
 *         &lt;element name="CostPrice" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BatchQuantity" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="AssembleAtDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{}BillOfMaterialItemDetails"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}ID"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "description",
    "costPrice",
    "batchQuantity",
    "assembleAtDelivery",
    "billOfMaterialItemDetails"
})
@XmlRootElement(name = "BillOfMaterial")
public class BillOfMaterial {

    @XmlElement(name = "Item", required = true)
    protected TypeItem item;
    @XmlElement(name = "Description")
    protected TypeDescription description;
    @XmlElement(name = "CostPrice")
    protected Float costPrice;
    @XmlElement(name = "BatchQuantity")
    protected float batchQuantity;
    @XmlElement(name = "AssembleAtDelivery")
    protected Boolean assembleAtDelivery;
    @XmlElement(name = "BillOfMaterialItemDetails", required = true)
    protected BillOfMaterialItemDetails billOfMaterialItemDetails;
    @XmlAttribute(name = "ID")
    protected String id;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setItem(TypeItem value) {
        this.item = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setDescription(TypeDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the costPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCostPrice() {
        return costPrice;
    }

    /**
     * Sets the value of the costPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCostPrice(Float value) {
        this.costPrice = value;
    }

    /**
     * Gets the value of the batchQuantity property.
     * 
     */
    public float getBatchQuantity() {
        return batchQuantity;
    }

    /**
     * Sets the value of the batchQuantity property.
     * 
     */
    public void setBatchQuantity(float value) {
        this.batchQuantity = value;
    }

    /**
     * Gets the value of the assembleAtDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAssembleAtDelivery() {
        return assembleAtDelivery;
    }

    /**
     * Sets the value of the assembleAtDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAssembleAtDelivery(Boolean value) {
        this.assembleAtDelivery = value;
    }

    /**
     * Gets the value of the billOfMaterialItemDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BillOfMaterialItemDetails }
     *     
     */
    public BillOfMaterialItemDetails getBillOfMaterialItemDetails() {
        return billOfMaterialItemDetails;
    }

    /**
     * Sets the value of the billOfMaterialItemDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillOfMaterialItemDetails }
     *     
     */
    public void setBillOfMaterialItemDetails(BillOfMaterialItemDetails value) {
        this.billOfMaterialItemDetails = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
