//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Budget" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Scenario">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}code use="required""/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="FinancialYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="BudgetLines">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BudgetLine" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}GLAccount"/>
 *                                       &lt;element ref="{}Costcenter" minOccurs="0"/>
 *                                       &lt;element ref="{}Costunit" minOccurs="0"/>
 *                                       &lt;element ref="{}Item" minOccurs="0"/>
 *                                       &lt;element name="Periods">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Period" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                         &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "budget"
})
@XmlRootElement(name = "Budgets")
public class Budgets {

    @XmlElement(name = "Budget")
    protected List<Budgets.Budget> budget;

    /**
     * Gets the value of the budget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the budget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBudget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Budgets.Budget }
     * 
     * 
     */
    public List<Budgets.Budget> getBudget() {
        if (budget == null) {
            budget = new ArrayList<Budgets.Budget>();
        }
        return this.budget;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Scenario">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}code use="required""/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="FinancialYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="BudgetLines">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BudgetLine" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}GLAccount"/>
     *                             &lt;element ref="{}Costcenter" minOccurs="0"/>
     *                             &lt;element ref="{}Costunit" minOccurs="0"/>
     *                             &lt;element ref="{}Item" minOccurs="0"/>
     *                             &lt;element name="Periods">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Period" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                               &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scenario",
        "financialYear",
        "budgetLines"
    })
    public static class Budget {

        @XmlElement(name = "Scenario", required = true)
        protected Budgets.Budget.Scenario scenario;
        @XmlElement(name = "FinancialYear", required = true)
        protected BigInteger financialYear;
        @XmlElement(name = "BudgetLines", required = true)
        protected Budgets.Budget.BudgetLines budgetLines;

        /**
         * Gets the value of the scenario property.
         * 
         * @return
         *     possible object is
         *     {@link Budgets.Budget.Scenario }
         *     
         */
        public Budgets.Budget.Scenario getScenario() {
            return scenario;
        }

        /**
         * Sets the value of the scenario property.
         * 
         * @param value
         *     allowed object is
         *     {@link Budgets.Budget.Scenario }
         *     
         */
        public void setScenario(Budgets.Budget.Scenario value) {
            this.scenario = value;
        }

        /**
         * Gets the value of the financialYear property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFinancialYear() {
            return financialYear;
        }

        /**
         * Sets the value of the financialYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFinancialYear(BigInteger value) {
            this.financialYear = value;
        }

        /**
         * Gets the value of the budgetLines property.
         * 
         * @return
         *     possible object is
         *     {@link Budgets.Budget.BudgetLines }
         *     
         */
        public Budgets.Budget.BudgetLines getBudgetLines() {
            return budgetLines;
        }

        /**
         * Sets the value of the budgetLines property.
         * 
         * @param value
         *     allowed object is
         *     {@link Budgets.Budget.BudgetLines }
         *     
         */
        public void setBudgetLines(Budgets.Budget.BudgetLines value) {
            this.budgetLines = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BudgetLine" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}GLAccount"/>
         *                   &lt;element ref="{}Costcenter" minOccurs="0"/>
         *                   &lt;element ref="{}Costunit" minOccurs="0"/>
         *                   &lt;element ref="{}Item" minOccurs="0"/>
         *                   &lt;element name="Periods">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Period" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                     &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "budgetLine"
        })
        public static class BudgetLines {

            @XmlElement(name = "BudgetLine", required = true)
            protected List<Budgets.Budget.BudgetLines.BudgetLine> budgetLine;

            /**
             * Gets the value of the budgetLine property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the budgetLine property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBudgetLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Budgets.Budget.BudgetLines.BudgetLine }
             * 
             * 
             */
            public List<Budgets.Budget.BudgetLines.BudgetLine> getBudgetLine() {
                if (budgetLine == null) {
                    budgetLine = new ArrayList<Budgets.Budget.BudgetLines.BudgetLine>();
                }
                return this.budgetLine;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}GLAccount"/>
             *         &lt;element ref="{}Costcenter" minOccurs="0"/>
             *         &lt;element ref="{}Costunit" minOccurs="0"/>
             *         &lt;element ref="{}Item" minOccurs="0"/>
             *         &lt;element name="Periods">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Period" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                           &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "glAccount",
                "costcenter",
                "costunit",
                "item",
                "periods"
            })
            public static class BudgetLine {

                @XmlElement(name = "GLAccount", required = true)
                protected TypeGLAccount glAccount;
                @XmlElement(name = "Costcenter")
                protected Costcenter costcenter;
                @XmlElement(name = "Costunit")
                protected Costunit costunit;
                @XmlElement(name = "Item")
                protected TypeItem item;
                @XmlElement(name = "Periods", required = true)
                protected Budgets.Budget.BudgetLines.BudgetLine.Periods periods;

                /**
                 * Gets the value of the glAccount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeGLAccount }
                 *     
                 */
                public TypeGLAccount getGLAccount() {
                    return glAccount;
                }

                /**
                 * Sets the value of the glAccount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeGLAccount }
                 *     
                 */
                public void setGLAccount(TypeGLAccount value) {
                    this.glAccount = value;
                }

                /**
                 * Gets the value of the costcenter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Costcenter }
                 *     
                 */
                public Costcenter getCostcenter() {
                    return costcenter;
                }

                /**
                 * Sets the value of the costcenter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Costcenter }
                 *     
                 */
                public void setCostcenter(Costcenter value) {
                    this.costcenter = value;
                }

                /**
                 * Gets the value of the costunit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Costunit }
                 *     
                 */
                public Costunit getCostunit() {
                    return costunit;
                }

                /**
                 * Sets the value of the costunit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Costunit }
                 *     
                 */
                public void setCostunit(Costunit value) {
                    this.costunit = value;
                }

                /**
                 * Gets the value of the item property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeItem }
                 *     
                 */
                public TypeItem getItem() {
                    return item;
                }

                /**
                 * Sets the value of the item property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeItem }
                 *     
                 */
                public void setItem(TypeItem value) {
                    this.item = value;
                }

                /**
                 * Gets the value of the periods property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Budgets.Budget.BudgetLines.BudgetLine.Periods }
                 *     
                 */
                public Budgets.Budget.BudgetLines.BudgetLine.Periods getPeriods() {
                    return periods;
                }

                /**
                 * Sets the value of the periods property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Budgets.Budget.BudgetLines.BudgetLine.Periods }
                 *     
                 */
                public void setPeriods(Budgets.Budget.BudgetLines.BudgetLine.Periods value) {
                    this.periods = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Period" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                 &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "period"
                })
                public static class Periods {

                    @XmlElement(name = "Period", required = true)
                    protected List<Budgets.Budget.BudgetLines.BudgetLine.Periods.Period> period;

                    /**
                     * Gets the value of the period property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the period property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPeriod().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Budgets.Budget.BudgetLines.BudgetLine.Periods.Period }
                     * 
                     * 
                     */
                    public List<Budgets.Budget.BudgetLines.BudgetLine.Periods.Period> getPeriod() {
                        if (period == null) {
                            period = new ArrayList<Budgets.Budget.BudgetLines.BudgetLine.Periods.Period>();
                        }
                        return this.period;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *       &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Period {

                        @XmlAttribute(required = true)
                        protected int value;
                        @XmlAttribute(required = true)
                        protected float amount;

                        /**
                         * Gets the value of the value property.
                         * 
                         */
                        public int getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         */
                        public void setValue(int value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the amount property.
                         * 
                         */
                        public float getAmount() {
                            return amount;
                        }

                        /**
                         * Sets the value of the amount property.
                         * 
                         */
                        public void setAmount(float value) {
                            this.amount = value;
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}code use="required""/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Scenario {

            @XmlAttribute(required = true)
            protected String code;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

        }

    }

}
