//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoilWireWeightShape complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoilWireWeightShape">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="StockToDimensionRatio" type="{}StockToDimensionRatioType"/>
 *           &lt;element name="DimensionToStockRatio" type="{}DimensionToStockRatioType"/>
 *         &lt;/choice>
 *         &lt;element name="Measurements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MeasurementUnit" type="{}WeightUnitOfMeasure" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CalculatedUnits" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Weight" type="{}WeightUnitOfMeasure" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoilWireWeightShape", propOrder = {
    "stockToDimensionRatio",
    "dimensionToStockRatio",
    "measurements",
    "calculatedUnits"
})
public class CoilWireWeightShape {

    @XmlElement(name = "StockToDimensionRatio")
    protected StockToDimensionRatioType stockToDimensionRatio;
    @XmlElement(name = "DimensionToStockRatio")
    protected DimensionToStockRatioType dimensionToStockRatio;
    @XmlElement(name = "Measurements")
    protected CoilWireWeightShape.Measurements measurements;
    @XmlElement(name = "CalculatedUnits")
    protected CoilWireWeightShape.CalculatedUnits calculatedUnits;

    /**
     * Gets the value of the stockToDimensionRatio property.
     * 
     * @return
     *     possible object is
     *     {@link StockToDimensionRatioType }
     *     
     */
    public StockToDimensionRatioType getStockToDimensionRatio() {
        return stockToDimensionRatio;
    }

    /**
     * Sets the value of the stockToDimensionRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockToDimensionRatioType }
     *     
     */
    public void setStockToDimensionRatio(StockToDimensionRatioType value) {
        this.stockToDimensionRatio = value;
    }

    /**
     * Gets the value of the dimensionToStockRatio property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionToStockRatioType }
     *     
     */
    public DimensionToStockRatioType getDimensionToStockRatio() {
        return dimensionToStockRatio;
    }

    /**
     * Sets the value of the dimensionToStockRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionToStockRatioType }
     *     
     */
    public void setDimensionToStockRatio(DimensionToStockRatioType value) {
        this.dimensionToStockRatio = value;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link CoilWireWeightShape.Measurements }
     *     
     */
    public CoilWireWeightShape.Measurements getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoilWireWeightShape.Measurements }
     *     
     */
    public void setMeasurements(CoilWireWeightShape.Measurements value) {
        this.measurements = value;
    }

    /**
     * Gets the value of the calculatedUnits property.
     * 
     * @return
     *     possible object is
     *     {@link CoilWireWeightShape.CalculatedUnits }
     *     
     */
    public CoilWireWeightShape.CalculatedUnits getCalculatedUnits() {
        return calculatedUnits;
    }

    /**
     * Sets the value of the calculatedUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoilWireWeightShape.CalculatedUnits }
     *     
     */
    public void setCalculatedUnits(CoilWireWeightShape.CalculatedUnits value) {
        this.calculatedUnits = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Weight" type="{}WeightUnitOfMeasure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "weight"
    })
    public static class CalculatedUnits {

        @XmlElement(name = "Weight")
        protected String weight;

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeight(String value) {
            this.weight = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MeasurementUnit" type="{}WeightUnitOfMeasure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "measurementUnit"
    })
    public static class Measurements {

        @XmlElement(name = "MeasurementUnit")
        protected String measurementUnit;

        /**
         * Gets the value of the measurementUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeasurementUnit() {
            return measurementUnit;
        }

        /**
         * Sets the value of the measurementUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeasurementUnit(String value) {
            this.measurementUnit = value;
        }

    }

}
