//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmountInclVAT" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="AmountExclVAT" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Percentage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amountInclVAT",
    "amountExclVAT",
    "percentage"
})
@XmlRootElement(name = "EntryDiscount")
public class EntryDiscount {

    @XmlElement(name = "AmountInclVAT")
    protected Object amountInclVAT;
    @XmlElement(name = "AmountExclVAT")
    protected Object amountExclVAT;
    @XmlElement(name = "Percentage")
    protected Object percentage;

    /**
     * Gets the value of the amountInclVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAmountInclVAT() {
        return amountInclVAT;
    }

    /**
     * Sets the value of the amountInclVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAmountInclVAT(Object value) {
        this.amountInclVAT = value;
    }

    /**
     * Gets the value of the amountExclVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAmountExclVAT() {
        return amountExclVAT;
    }

    /**
     * Sets the value of the amountExclVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAmountExclVAT(Object value) {
        this.amountExclVAT = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPercentage(Object value) {
        this.percentage = value;
    }

}
