//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="AssemblyDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}SerialNumbers" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}BatchNumbers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="ordernumber" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="assemblynumber" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assemblyDate",
    "quantity",
    "serialNumbers",
    "batchNumbers"
})
@XmlRootElement(name = "FinishedAssembly")
public class FinishedAssembly {

    @XmlElement(name = "AssemblyDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar assemblyDate;
    @XmlElement(name = "Quantity")
    protected Float quantity;
    @XmlElement(name = "SerialNumbers")
    protected List<SerialNumbers> serialNumbers;
    @XmlElement(name = "BatchNumbers")
    protected List<BatchNumbers> batchNumbers;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String ordernumber;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String assemblynumber;

    /**
     * Gets the value of the assemblyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssemblyDate() {
        return assemblyDate;
    }

    /**
     * Sets the value of the assemblyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssemblyDate(XMLGregorianCalendar value) {
        this.assemblyDate = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setQuantity(Float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the serialNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serialNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSerialNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SerialNumbers }
     * 
     * 
     */
    public List<SerialNumbers> getSerialNumbers() {
        if (serialNumbers == null) {
            serialNumbers = new ArrayList<SerialNumbers>();
        }
        return this.serialNumbers;
    }

    /**
     * Gets the value of the batchNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batchNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatchNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchNumbers }
     * 
     * 
     */
    public List<BatchNumbers> getBatchNumbers() {
        if (batchNumbers == null) {
            batchNumbers = new ArrayList<BatchNumbers>();
        }
        return this.batchNumbers;
    }

    /**
     * Gets the value of the ordernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * Sets the value of the ordernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdernumber(String value) {
        this.ordernumber = value;
    }

    /**
     * Gets the value of the assemblynumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemblynumber() {
        return assemblynumber;
    }

    /**
     * Sets the value of the assemblynumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemblynumber(String value) {
        this.assemblynumber = value;
    }

}
