//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Item" minOccurs="0"/>
 *         &lt;element ref="{}Warehouse" minOccurs="0"/>
 *         &lt;element ref="{}StorageLocation" minOccurs="0"/>
 *         &lt;element name="ReorderPoint" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="MaximumStock" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ItemWarehouse")
public class ItemWarehouse {

    @XmlElement(name = "Item")
    protected TypeItem item;
    @XmlElement(name = "Warehouse")
    protected Warehouse warehouse;
    @XmlElement(name = "StorageLocation")
    protected StorageLocation storageLocation;
    @XmlElement(name = "ReorderPoint")
    protected float reorderPoint;
    @XmlElement(name = "MaximumStock")
    protected Float maximumStock;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setItem(TypeItem value) {
        this.item = value;
    }

    /**
     * Gets the value of the warehouse property.
     * 
     * @return
     *     possible object is
     *     {@link Warehouse }
     *     
     */
    public Warehouse getWarehouse() {
        return warehouse;
    }

    /**
     * Sets the value of the warehouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Warehouse }
     *     
     */
    public void setWarehouse(Warehouse value) {
        this.warehouse = value;
    }

    /**
     * Gets the value of the storageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link StorageLocation }
     *     
     */
    public StorageLocation getStorageLocation() {
        return storageLocation;
    }

    /**
     * Sets the value of the storageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageLocation }
     *     
     */
    public void setStorageLocation(StorageLocation value) {
        this.storageLocation = value;
    }

    /**
     * Gets the value of the reorderPoint property.
     * 
     */
    public float getReorderPoint() {
        return reorderPoint;
    }

    /**
     * Sets the value of the reorderPoint property.
     * 
     */
    public void setReorderPoint(float value) {
        this.reorderPoint = value;
    }

    /**
     * Gets the value of the maximumStock property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMaximumStock() {
        return maximumStock;
    }

    /**
     * Sets the value of the maximumStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMaximumStock(Float value) {
        this.maximumStock = value;
    }

}
