//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="finyear" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="finperiod" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="journal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entry" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="amountdc" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MatchLine")
public class MatchLine {

    @XmlAttribute(required = true)
    protected BigInteger finyear;
    @XmlAttribute(required = true)
    protected BigInteger finperiod;
    @XmlAttribute(required = true)
    protected String journal;
    @XmlAttribute(required = true)
    protected BigInteger entry;
    @XmlAttribute(required = true)
    protected float amountdc;

    /**
     * Gets the value of the finyear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinyear() {
        return finyear;
    }

    /**
     * Sets the value of the finyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinyear(BigInteger value) {
        this.finyear = value;
    }

    /**
     * Gets the value of the finperiod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFinperiod() {
        return finperiod;
    }

    /**
     * Sets the value of the finperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFinperiod(BigInteger value) {
        this.finperiod = value;
    }

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournal(String value) {
        this.journal = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEntry() {
        return entry;
    }

    /**
     * Sets the value of the entry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEntry(BigInteger value) {
        this.entry = value;
    }

    /**
     * Gets the value of the amountdc property.
     * 
     */
    public float getAmountdc() {
        return amountdc;
    }

    /**
     * Sets the value of the amountdc property.
     * 
     */
    public void setAmountdc(float value) {
        this.amountdc = value;
    }

}
