//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{}Item"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}SerialNumbers"/>
 *           &lt;element ref="{}BatchNumbers"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemAndSerialNumbersOrBatchNumbers"
})
@XmlRootElement(name = "Part")
public class Part {

    @XmlElements({
        @XmlElement(name = "BatchNumbers", required = true, type = BatchNumbers.class),
        @XmlElement(name = "Item", required = true, type = TypeItem.class),
        @XmlElement(name = "SerialNumbers", required = true, type = SerialNumbers.class)
    })
    protected List<Object> itemAndSerialNumbersOrBatchNumbers;

    /**
     * Gets the value of the itemAndSerialNumbersOrBatchNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemAndSerialNumbersOrBatchNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemAndSerialNumbersOrBatchNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchNumbers }
     * {@link TypeItem }
     * {@link SerialNumbers }
     * 
     * 
     */
    public List<Object> getItemAndSerialNumbersOrBatchNumbers() {
        if (itemAndSerialNumbersOrBatchNumbers == null) {
            itemAndSerialNumbersOrBatchNumbers = new ArrayList<Object>();
        }
        return this.itemAndSerialNumbersOrBatchNumbers;
    }

}
