//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="HourType" type="{}typeItem"/>
 *         &lt;element name="BudgetedHours" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hourType",
    "budgetedHours"
})
@XmlRootElement(name = "ProjectBudgetedHourType")
public class ProjectBudgetedHourType {

    @XmlElement(name = "HourType")
    protected TypeItem hourType;
    @XmlElement(name = "BudgetedHours")
    protected Float budgetedHours;
    @XmlAttribute(name = "ID")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the hourType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getHourType() {
        return hourType;
    }

    /**
     * Sets the value of the hourType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setHourType(TypeItem value) {
        this.hourType = value;
    }

    /**
     * Gets the value of the budgetedHours property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBudgetedHours() {
        return budgetedHours;
    }

    /**
     * Sets the value of the budgetedHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBudgetedHours(Float value) {
        this.budgetedHours = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
