//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Translations" minOccurs="0"/>
 *         &lt;element ref="{}Account" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ProjectManager" type="{}typeUser" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BudgetedTime" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BudgetedAmount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="AlertTime" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FixedPriceItem" type="{}typeItem" minOccurs="0"/>
 *         &lt;element ref="{}ProjectClassification" minOccurs="0"/>
 *         &lt;element name="CustomerPONumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrepaidType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrepaidItem" type="{}typeItem" minOccurs="0"/>
 *         &lt;element name="MarkupPercentage" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BudgetedCosts" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="BudgetedRevenue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element ref="{}Items" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RebillableItems" type="{}typeItems" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Employees" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProjectInvoiceTerms" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProjectBudgetedHourTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BlockEntry" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="BlockRebilling" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}code use="required""/>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "translations",
    "account",
    "startDate",
    "endDate",
    "projectManager",
    "notes",
    "budgetedTime",
    "budgetedAmount",
    "alertTime",
    "fixedPriceItem",
    "projectClassification",
    "customerPONumber",
    "prepaidType",
    "prepaidItem",
    "markupPercentage",
    "budgetedCosts",
    "budgetedRevenue",
    "items",
    "rebillableItems",
    "employees",
    "projectInvoiceTerms",
    "projectBudgetedHourTypes",
    "blockEntry",
    "blockRebilling"
})
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Translations")
    protected Translations translations;
    @XmlElement(name = "Account")
    protected TypeAccount account;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "ProjectManager")
    protected TypeUser projectManager;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "BudgetedTime")
    protected Float budgetedTime;
    @XmlElement(name = "BudgetedAmount")
    protected Float budgetedAmount;
    @XmlElement(name = "AlertTime")
    protected Float alertTime;
    @XmlElement(name = "FixedPriceItem")
    protected TypeItem fixedPriceItem;
    @XmlElement(name = "ProjectClassification")
    protected ProjectClassification projectClassification;
    @XmlElement(name = "CustomerPONumber")
    protected String customerPONumber;
    @XmlElement(name = "PrepaidType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String prepaidType;
    @XmlElement(name = "PrepaidItem")
    protected TypeItem prepaidItem;
    @XmlElement(name = "MarkupPercentage")
    protected Float markupPercentage;
    @XmlElement(name = "BudgetedCosts")
    protected Float budgetedCosts;
    @XmlElement(name = "BudgetedRevenue")
    protected Float budgetedRevenue;
    @XmlElement(name = "Items")
    protected List<Items> items;
    @XmlElement(name = "RebillableItems")
    protected List<TypeItems> rebillableItems;
    @XmlElement(name = "Employees")
    protected List<Employees> employees;
    @XmlElement(name = "ProjectInvoiceTerms")
    protected List<ProjectInvoiceTerms> projectInvoiceTerms;
    @XmlElement(name = "ProjectBudgetedHourTypes")
    protected List<ProjectBudgetedHourTypes> projectBudgetedHourTypes;
    @XmlElement(name = "BlockEntry")
    protected Boolean blockEntry;
    @XmlElement(name = "BlockRebilling")
    protected Boolean blockRebilling;
    @XmlAttribute(required = true)
    protected String code;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the translations property.
     * 
     * @return
     *     possible object is
     *     {@link Translations }
     *     
     */
    public Translations getTranslations() {
        return translations;
    }

    /**
     * Sets the value of the translations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Translations }
     *     
     */
    public void setTranslations(Translations value) {
        this.translations = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setAccount(TypeAccount value) {
        this.account = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the projectManager property.
     * 
     * @return
     *     possible object is
     *     {@link TypeUser }
     *     
     */
    public TypeUser getProjectManager() {
        return projectManager;
    }

    /**
     * Sets the value of the projectManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeUser }
     *     
     */
    public void setProjectManager(TypeUser value) {
        this.projectManager = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the budgetedTime property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBudgetedTime() {
        return budgetedTime;
    }

    /**
     * Sets the value of the budgetedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBudgetedTime(Float value) {
        this.budgetedTime = value;
    }

    /**
     * Gets the value of the budgetedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBudgetedAmount() {
        return budgetedAmount;
    }

    /**
     * Sets the value of the budgetedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBudgetedAmount(Float value) {
        this.budgetedAmount = value;
    }

    /**
     * Gets the value of the alertTime property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getAlertTime() {
        return alertTime;
    }

    /**
     * Sets the value of the alertTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setAlertTime(Float value) {
        this.alertTime = value;
    }

    /**
     * Gets the value of the fixedPriceItem property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getFixedPriceItem() {
        return fixedPriceItem;
    }

    /**
     * Sets the value of the fixedPriceItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setFixedPriceItem(TypeItem value) {
        this.fixedPriceItem = value;
    }

    /**
     * Gets the value of the projectClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectClassification }
     *     
     */
    public ProjectClassification getProjectClassification() {
        return projectClassification;
    }

    /**
     * Sets the value of the projectClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectClassification }
     *     
     */
    public void setProjectClassification(ProjectClassification value) {
        this.projectClassification = value;
    }

    /**
     * Gets the value of the customerPONumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPONumber() {
        return customerPONumber;
    }

    /**
     * Sets the value of the customerPONumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPONumber(String value) {
        this.customerPONumber = value;
    }

    /**
     * Gets the value of the prepaidType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrepaidType() {
        return prepaidType;
    }

    /**
     * Sets the value of the prepaidType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrepaidType(String value) {
        this.prepaidType = value;
    }

    /**
     * Gets the value of the prepaidItem property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getPrepaidItem() {
        return prepaidItem;
    }

    /**
     * Sets the value of the prepaidItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setPrepaidItem(TypeItem value) {
        this.prepaidItem = value;
    }

    /**
     * Gets the value of the markupPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMarkupPercentage() {
        return markupPercentage;
    }

    /**
     * Sets the value of the markupPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMarkupPercentage(Float value) {
        this.markupPercentage = value;
    }

    /**
     * Gets the value of the budgetedCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBudgetedCosts() {
        return budgetedCosts;
    }

    /**
     * Sets the value of the budgetedCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBudgetedCosts(Float value) {
        this.budgetedCosts = value;
    }

    /**
     * Gets the value of the budgetedRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBudgetedRevenue() {
        return budgetedRevenue;
    }

    /**
     * Sets the value of the budgetedRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBudgetedRevenue(Float value) {
        this.budgetedRevenue = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the items property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Items }
     * 
     * 
     */
    public List<Items> getItems() {
        if (items == null) {
            items = new ArrayList<Items>();
        }
        return this.items;
    }

    /**
     * Gets the value of the rebillableItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rebillableItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRebillableItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeItems }
     * 
     * 
     */
    public List<TypeItems> getRebillableItems() {
        if (rebillableItems == null) {
            rebillableItems = new ArrayList<TypeItems>();
        }
        return this.rebillableItems;
    }

    /**
     * Gets the value of the employees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the employees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmployees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Employees }
     * 
     * 
     */
    public List<Employees> getEmployees() {
        if (employees == null) {
            employees = new ArrayList<Employees>();
        }
        return this.employees;
    }

    /**
     * Gets the value of the projectInvoiceTerms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectInvoiceTerms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectInvoiceTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectInvoiceTerms }
     * 
     * 
     */
    public List<ProjectInvoiceTerms> getProjectInvoiceTerms() {
        if (projectInvoiceTerms == null) {
            projectInvoiceTerms = new ArrayList<ProjectInvoiceTerms>();
        }
        return this.projectInvoiceTerms;
    }

    /**
     * Gets the value of the projectBudgetedHourTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectBudgetedHourTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectBudgetedHourTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectBudgetedHourTypes }
     * 
     * 
     */
    public List<ProjectBudgetedHourTypes> getProjectBudgetedHourTypes() {
        if (projectBudgetedHourTypes == null) {
            projectBudgetedHourTypes = new ArrayList<ProjectBudgetedHourTypes>();
        }
        return this.projectBudgetedHourTypes;
    }

    /**
     * Gets the value of the blockEntry property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlockEntry() {
        return blockEntry;
    }

    /**
     * Sets the value of the blockEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlockEntry(Boolean value) {
        this.blockEntry = value;
    }

    /**
     * Gets the value of the blockRebilling property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlockRebilling() {
        return blockRebilling;
    }

    /**
     * Sets the value of the blockRebilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlockRebilling(Boolean value) {
        this.blockRebilling = value;
    }

    /**
     * Unique number indentifying the entry
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
