//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderedBy" type="{}typeAccount"/>
 *         &lt;element name="OrderContact" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="HID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InvoiceTo" type="{}typeAccount"/>
 *         &lt;element name="InvoiceContact" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="HID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}Description" minOccurs="0"/>
 *         &lt;element name="QuotationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ClosingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element ref="{}ForeignAmount"/>
 *         &lt;element ref="{}PaymentCondition" minOccurs="0"/>
 *         &lt;element ref="{}Opportunity" minOccurs="0"/>
 *         &lt;element ref="{}YourRef" minOccurs="0"/>
 *         &lt;element name="SalesPerson" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}EntryDiscount" minOccurs="0"/>
 *         &lt;element name="QuotationLine" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Description" minOccurs="0"/>
 *                   &lt;element ref="{}Item"/>
 *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{}Description" minOccurs="0"/>
 *                   &lt;element ref="{}StartDate" minOccurs="0"/>
 *                   &lt;element ref="{}EndDate" minOccurs="0"/>
 *                   &lt;element ref="{}Quantity" minOccurs="0"/>
 *                   &lt;element name="UnitPrice" type="{}typePrice" minOccurs="0"/>
 *                   &lt;element name="DiscountPercentage" type="{}typePercentage" minOccurs="0"/>
 *                   &lt;element name="NetPrice" type="{}typePrice" minOccurs="0"/>
 *                   &lt;element ref="{}Unit" minOccurs="0"/>
 *                   &lt;element ref="{}ForeignAmount" minOccurs="0"/>
 *                   &lt;element ref="{}Costcenter" minOccurs="0"/>
 *                   &lt;element ref="{}Costunit" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CloseDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{}Project" minOccurs="0"/>
 *         &lt;element ref="{}ShippingMethod" minOccurs="0"/>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="quotationnumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderedBy",
    "orderContact",
    "invoiceTo",
    "invoiceContact",
    "description",
    "quotationDate",
    "dueDate",
    "closingDate",
    "foreignAmount",
    "paymentCondition",
    "opportunity",
    "yourRef",
    "salesPerson",
    "notes",
    "entryDiscount",
    "quotationLine",
    "closeDate",
    "source",
    "project",
    "shippingMethod",
    "deliveryDate"
})
@XmlRootElement(name = "Quotation")
public class Quotation {

    @XmlElement(name = "OrderedBy", required = true)
    protected TypeAccount orderedBy;
    @XmlElement(name = "OrderContact")
    protected Quotation.OrderContact orderContact;
    @XmlElement(name = "InvoiceTo", required = true)
    protected TypeAccount invoiceTo;
    @XmlElement(name = "InvoiceContact")
    protected Quotation.InvoiceContact invoiceContact;
    @XmlElement(name = "Description")
    protected TypeDescription description;
    @XmlElement(name = "QuotationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar quotationDate;
    @XmlElement(name = "DueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "ClosingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar closingDate;
    @XmlElement(name = "ForeignAmount", required = true)
    protected ForeignAmount foreignAmount;
    @XmlElement(name = "PaymentCondition")
    protected PaymentCondition paymentCondition;
    @XmlElement(name = "Opportunity")
    protected Opportunity opportunity;
    @XmlElement(name = "YourRef")
    protected String yourRef;
    @XmlElement(name = "SalesPerson")
    protected Quotation.SalesPerson salesPerson;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "EntryDiscount")
    protected EntryDiscount entryDiscount;
    @XmlElement(name = "QuotationLine", required = true)
    protected List<Quotation.QuotationLine> quotationLine;
    @XmlElement(name = "CloseDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar closeDate;
    @XmlElement(name = "Source", required = true)
    protected BigInteger source;
    @XmlElement(name = "Project")
    protected Project project;
    @XmlElement(name = "ShippingMethod")
    protected ShippingMethod shippingMethod;
    @XmlElement(name = "DeliveryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlAttribute(required = true)
    protected BigInteger quotationnumber;
    @XmlAttribute
    protected BigInteger status;

    /**
     * Gets the value of the orderedBy property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getOrderedBy() {
        return orderedBy;
    }

    /**
     * Sets the value of the orderedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setOrderedBy(TypeAccount value) {
        this.orderedBy = value;
    }

    /**
     * Gets the value of the orderContact property.
     * 
     * @return
     *     possible object is
     *     {@link Quotation.OrderContact }
     *     
     */
    public Quotation.OrderContact getOrderContact() {
        return orderContact;
    }

    /**
     * Sets the value of the orderContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quotation.OrderContact }
     *     
     */
    public void setOrderContact(Quotation.OrderContact value) {
        this.orderContact = value;
    }

    /**
     * Gets the value of the invoiceTo property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getInvoiceTo() {
        return invoiceTo;
    }

    /**
     * Sets the value of the invoiceTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setInvoiceTo(TypeAccount value) {
        this.invoiceTo = value;
    }

    /**
     * Gets the value of the invoiceContact property.
     * 
     * @return
     *     possible object is
     *     {@link Quotation.InvoiceContact }
     *     
     */
    public Quotation.InvoiceContact getInvoiceContact() {
        return invoiceContact;
    }

    /**
     * Sets the value of the invoiceContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quotation.InvoiceContact }
     *     
     */
    public void setInvoiceContact(Quotation.InvoiceContact value) {
        this.invoiceContact = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDescription }
     *     
     */
    public TypeDescription getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDescription }
     *     
     */
    public void setDescription(TypeDescription value) {
        this.description = value;
    }

    /**
     * Gets the value of the quotationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getQuotationDate() {
        return quotationDate;
    }

    /**
     * Sets the value of the quotationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setQuotationDate(XMLGregorianCalendar value) {
        this.quotationDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the closingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getClosingDate() {
        return closingDate;
    }

    /**
     * Sets the value of the closingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setClosingDate(XMLGregorianCalendar value) {
        this.closingDate = value;
    }

    /**
     * Gets the value of the foreignAmount property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignAmount }
     *     
     */
    public ForeignAmount getForeignAmount() {
        return foreignAmount;
    }

    /**
     * Sets the value of the foreignAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignAmount }
     *     
     */
    public void setForeignAmount(ForeignAmount value) {
        this.foreignAmount = value;
    }

    /**
     * Gets the value of the paymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCondition }
     *     
     */
    public PaymentCondition getPaymentCondition() {
        return paymentCondition;
    }

    /**
     * Sets the value of the paymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCondition }
     *     
     */
    public void setPaymentCondition(PaymentCondition value) {
        this.paymentCondition = value;
    }

    /**
     * Gets the value of the opportunity property.
     * 
     * @return
     *     possible object is
     *     {@link Opportunity }
     *     
     */
    public Opportunity getOpportunity() {
        return opportunity;
    }

    /**
     * Sets the value of the opportunity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Opportunity }
     *     
     */
    public void setOpportunity(Opportunity value) {
        this.opportunity = value;
    }

    /**
     * Gets the value of the yourRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYourRef() {
        return yourRef;
    }

    /**
     * Sets the value of the yourRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYourRef(String value) {
        this.yourRef = value;
    }

    /**
     * Gets the value of the salesPerson property.
     * 
     * @return
     *     possible object is
     *     {@link Quotation.SalesPerson }
     *     
     */
    public Quotation.SalesPerson getSalesPerson() {
        return salesPerson;
    }

    /**
     * Sets the value of the salesPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quotation.SalesPerson }
     *     
     */
    public void setSalesPerson(Quotation.SalesPerson value) {
        this.salesPerson = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the entryDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link EntryDiscount }
     *     
     */
    public EntryDiscount getEntryDiscount() {
        return entryDiscount;
    }

    /**
     * Sets the value of the entryDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryDiscount }
     *     
     */
    public void setEntryDiscount(EntryDiscount value) {
        this.entryDiscount = value;
    }

    /**
     * Gets the value of the quotationLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quotationLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuotationLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quotation.QuotationLine }
     * 
     * 
     */
    public List<Quotation.QuotationLine> getQuotationLine() {
        if (quotationLine == null) {
            quotationLine = new ArrayList<Quotation.QuotationLine>();
        }
        return this.quotationLine;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCloseDate(XMLGregorianCalendar value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSource(BigInteger value) {
        this.source = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public Project getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project }
     *     
     */
    public void setProject(Project value) {
        this.project = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingMethod }
     *     
     */
    public ShippingMethod getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingMethod }
     *     
     */
    public void setShippingMethod(ShippingMethod value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the quotationnumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuotationnumber() {
        return quotationnumber;
    }

    /**
     * Sets the value of the quotationnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuotationnumber(BigInteger value) {
        this.quotationnumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="HID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lastName",
        "firstName"
    })
    public static class InvoiceContact {

        @XmlElement(name = "LastName")
        protected String lastName;
        @XmlElement(name = "FirstName")
        protected String firstName;
        @XmlAttribute(name = "ID", required = true)
        protected String id;
        @XmlAttribute(name = "HID", required = true)
        protected BigInteger hid;

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the hid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getHID() {
            return hid;
        }

        /**
         * Sets the value of the hid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setHID(BigInteger value) {
            this.hid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="HID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lastName",
        "firstName"
    })
    public static class OrderContact {

        @XmlElement(name = "LastName")
        protected String lastName;
        @XmlElement(name = "FirstName")
        protected String firstName;
        @XmlAttribute(name = "ID", required = true)
        protected String id;
        @XmlAttribute(name = "HID", required = true)
        protected BigInteger hid;

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the hid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getHID() {
            return hid;
        }

        /**
         * Sets the value of the hid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setHID(BigInteger value) {
            this.hid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Description" minOccurs="0"/>
     *         &lt;element ref="{}Item"/>
     *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{}Description" minOccurs="0"/>
     *         &lt;element ref="{}StartDate" minOccurs="0"/>
     *         &lt;element ref="{}EndDate" minOccurs="0"/>
     *         &lt;element ref="{}Quantity" minOccurs="0"/>
     *         &lt;element name="UnitPrice" type="{}typePrice" minOccurs="0"/>
     *         &lt;element name="DiscountPercentage" type="{}typePercentage" minOccurs="0"/>
     *         &lt;element name="NetPrice" type="{}typePrice" minOccurs="0"/>
     *         &lt;element ref="{}Unit" minOccurs="0"/>
     *         &lt;element ref="{}ForeignAmount" minOccurs="0"/>
     *         &lt;element ref="{}Costcenter" minOccurs="0"/>
     *         &lt;element ref="{}Costunit" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class QuotationLine {

        @XmlElementRefs({
            @XmlElementRef(name = "DiscountPercentage", type = JAXBElement.class),
            @XmlElementRef(name = "Unit", type = Unit.class),
            @XmlElementRef(name = "Quantity", type = JAXBElement.class),
            @XmlElementRef(name = "Description", type = JAXBElement.class),
            @XmlElementRef(name = "Item", type = JAXBElement.class),
            @XmlElementRef(name = "ForeignAmount", type = ForeignAmount.class),
            @XmlElementRef(name = "NetPrice", type = JAXBElement.class),
            @XmlElementRef(name = "Notes", type = JAXBElement.class),
            @XmlElementRef(name = "Costcenter", type = Costcenter.class),
            @XmlElementRef(name = "StartDate", type = JAXBElement.class),
            @XmlElementRef(name = "EndDate", type = JAXBElement.class),
            @XmlElementRef(name = "Costunit", type = Costunit.class),
            @XmlElementRef(name = "UnitPrice", type = JAXBElement.class)
        })
        protected List<Object> content;
        @XmlAttribute
        protected BigInteger line;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Description" is used by two different parts of a schema. See: 
         * line 5261 of file:/Users/marten/Sites/eExact-XML.xsd
         * line 5258 of file:/Users/marten/Sites/eExact-XML.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Float }{@code >}
         * {@link Unit }
         * {@link JAXBElement }{@code <}{@link Float }{@code >}
         * {@link JAXBElement }{@code <}{@link TypeDescription }{@code >}
         * {@link JAXBElement }{@code <}{@link TypeItem }{@code >}
         * {@link ForeignAmount }
         * {@link JAXBElement }{@code <}{@link TypePrice }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link Costcenter }
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link Costunit }
         * {@link JAXBElement }{@code <}{@link TypePrice }{@code >}
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

        /**
         * Gets the value of the line property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLine() {
            return line;
        }

        /**
         * Sets the value of the line property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLine(BigInteger value) {
            this.line = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName"
    })
    public static class SalesPerson {

        @XmlElement(name = "FullName")
        protected String fullName;
        @XmlAttribute(required = true)
        protected String id;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
