//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Item"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}SerialNumbers"/>
 *           &lt;element ref="{}BatchNumbers"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="PurchaseOrderNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PurchaseOrderLine" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="ReceiptDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "serialNumbers",
    "batchNumbers"
})
@XmlRootElement(name = "ReceiptLine")
public class ReceiptLine {

    @XmlElement(name = "Item", required = true)
    protected TypeItem item;
    @XmlElement(name = "SerialNumbers")
    protected SerialNumbers serialNumbers;
    @XmlElement(name = "BatchNumbers")
    protected BatchNumbers batchNumbers;
    @XmlAttribute(name = "PurchaseOrderNumber", required = true)
    protected BigInteger purchaseOrderNumber;
    @XmlAttribute(name = "PurchaseOrderLine")
    protected BigInteger purchaseOrderLine;
    @XmlAttribute(name = "Quantity", required = true)
    protected float quantity;
    @XmlAttribute(name = "ReceiptDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar receiptDate;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link TypeItem }
     *     
     */
    public TypeItem getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeItem }
     *     
     */
    public void setItem(TypeItem value) {
        this.item = value;
    }

    /**
     * Gets the value of the serialNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumbers }
     *     
     */
    public SerialNumbers getSerialNumbers() {
        return serialNumbers;
    }

    /**
     * Sets the value of the serialNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumbers }
     *     
     */
    public void setSerialNumbers(SerialNumbers value) {
        this.serialNumbers = value;
    }

    /**
     * Gets the value of the batchNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link BatchNumbers }
     *     
     */
    public BatchNumbers getBatchNumbers() {
        return batchNumbers;
    }

    /**
     * Sets the value of the batchNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatchNumbers }
     *     
     */
    public void setBatchNumbers(BatchNumbers value) {
        this.batchNumbers = value;
    }

    /**
     * Gets the value of the purchaseOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPurchaseOrderNumber() {
        return purchaseOrderNumber;
    }

    /**
     * Sets the value of the purchaseOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPurchaseOrderNumber(BigInteger value) {
        this.purchaseOrderNumber = value;
    }

    /**
     * Gets the value of the purchaseOrderLine property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPurchaseOrderLine() {
        return purchaseOrderLine;
    }

    /**
     * Sets the value of the purchaseOrderLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPurchaseOrderLine(BigInteger value) {
        this.purchaseOrderLine = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the receiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceiptDate() {
        return receiptDate;
    }

    /**
     * Sets the value of the receiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceiptDate(XMLGregorianCalendar value) {
        this.receiptDate = value;
    }

}
