//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SubscriptionType" minOccurs="0"/>
 *         &lt;element ref="{}StartDate" minOccurs="0"/>
 *         &lt;element ref="{}EndDate" minOccurs="0"/>
 *         &lt;element name="CancellationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="OrderedBy" type="{}typeAccount" minOccurs="0"/>
 *         &lt;element name="InvoicedTo" type="{}typeAccount" minOccurs="0"/>
 *         &lt;element ref="{}Contact" minOccurs="0"/>
 *         &lt;element ref="{}PaymentCondition" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerPONumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}SubscriptionClassification" minOccurs="0"/>
 *         &lt;element name="SubscriptionLine" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Description"/>
 *                   &lt;element ref="{}Item"/>
 *                   &lt;element ref="{}Quantity"/>
 *                   &lt;element ref="{}Unit"/>
 *                   &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="NetPrice" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element ref="{}VAT" minOccurs="0"/>
 *                   &lt;element name="DiscountPercentage" type="{}typePercentage" minOccurs="0"/>
 *                   &lt;element ref="{}StartDate" minOccurs="0"/>
 *                   &lt;element ref="{}EndDate" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="entryID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "subscriptionType",
    "startDate",
    "endDate",
    "cancellationDate",
    "orderedBy",
    "invoicedTo",
    "contact",
    "paymentCondition",
    "notes",
    "customerPONumber",
    "subscriptionClassification",
    "subscriptionLine"
})
@XmlRootElement(name = "Subscription")
public class Subscription {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "SubscriptionType")
    protected SubscriptionType subscriptionType;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "CancellationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cancellationDate;
    @XmlElement(name = "OrderedBy")
    protected TypeAccount orderedBy;
    @XmlElement(name = "InvoicedTo")
    protected TypeAccount invoicedTo;
    @XmlElement(name = "Contact")
    protected Contact contact;
    @XmlElement(name = "PaymentCondition")
    protected PaymentCondition paymentCondition;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "CustomerPONumber")
    protected String customerPONumber;
    @XmlElement(name = "SubscriptionClassification")
    protected SubscriptionClassification subscriptionClassification;
    @XmlElement(name = "SubscriptionLine")
    protected List<Subscription.SubscriptionLine> subscriptionLine;
    @XmlAttribute(name = "Number", required = true)
    protected BigInteger number;
    @XmlAttribute
    protected String entryID;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the subscriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionType }
     *     
     */
    public SubscriptionType getSubscriptionType() {
        return subscriptionType;
    }

    /**
     * Sets the value of the subscriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionType }
     *     
     */
    public void setSubscriptionType(SubscriptionType value) {
        this.subscriptionType = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the cancellationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCancellationDate() {
        return cancellationDate;
    }

    /**
     * Sets the value of the cancellationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCancellationDate(XMLGregorianCalendar value) {
        this.cancellationDate = value;
    }

    /**
     * Gets the value of the orderedBy property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getOrderedBy() {
        return orderedBy;
    }

    /**
     * Sets the value of the orderedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setOrderedBy(TypeAccount value) {
        this.orderedBy = value;
    }

    /**
     * Gets the value of the invoicedTo property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAccount }
     *     
     */
    public TypeAccount getInvoicedTo() {
        return invoicedTo;
    }

    /**
     * Sets the value of the invoicedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAccount }
     *     
     */
    public void setInvoicedTo(TypeAccount value) {
        this.invoicedTo = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link Contact }
     *     
     */
    public Contact getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contact }
     *     
     */
    public void setContact(Contact value) {
        this.contact = value;
    }

    /**
     * Gets the value of the paymentCondition property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCondition }
     *     
     */
    public PaymentCondition getPaymentCondition() {
        return paymentCondition;
    }

    /**
     * Sets the value of the paymentCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCondition }
     *     
     */
    public void setPaymentCondition(PaymentCondition value) {
        this.paymentCondition = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the customerPONumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPONumber() {
        return customerPONumber;
    }

    /**
     * Sets the value of the customerPONumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPONumber(String value) {
        this.customerPONumber = value;
    }

    /**
     * Gets the value of the subscriptionClassification property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionClassification }
     *     
     */
    public SubscriptionClassification getSubscriptionClassification() {
        return subscriptionClassification;
    }

    /**
     * Sets the value of the subscriptionClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionClassification }
     *     
     */
    public void setSubscriptionClassification(SubscriptionClassification value) {
        this.subscriptionClassification = value;
    }

    /**
     * Gets the value of the subscriptionLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriptionLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriptionLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscription.SubscriptionLine }
     * 
     * 
     */
    public List<Subscription.SubscriptionLine> getSubscriptionLine() {
        if (subscriptionLine == null) {
            subscriptionLine = new ArrayList<Subscription.SubscriptionLine>();
        }
        return this.subscriptionLine;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the entryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryID() {
        return entryID;
    }

    /**
     * Sets the value of the entryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryID(String value) {
        this.entryID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Description"/>
     *         &lt;element ref="{}Item"/>
     *         &lt;element ref="{}Quantity"/>
     *         &lt;element ref="{}Unit"/>
     *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="NetPrice" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element ref="{}VAT" minOccurs="0"/>
     *         &lt;element name="DiscountPercentage" type="{}typePercentage" minOccurs="0"/>
     *         &lt;element ref="{}StartDate" minOccurs="0"/>
     *         &lt;element ref="{}EndDate" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "item",
        "quantity",
        "unit",
        "unitPrice",
        "netPrice",
        "vat",
        "discountPercentage",
        "startDate",
        "endDate"
    })
    public static class SubscriptionLine {

        @XmlElement(name = "Description", required = true)
        protected TypeDescription description;
        @XmlElement(name = "Item", required = true)
        protected TypeItem item;
        @XmlElement(name = "Quantity")
        protected float quantity;
        @XmlElement(name = "Unit", required = true)
        protected Unit unit;
        @XmlElement(name = "UnitPrice")
        protected Float unitPrice;
        @XmlElement(name = "NetPrice")
        protected Float netPrice;
        @XmlElement(name = "VAT")
        protected VAT vat;
        @XmlElement(name = "DiscountPercentage")
        protected Float discountPercentage;
        @XmlElement(name = "StartDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "EndDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlAttribute
        protected BigInteger line;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link TypeDescription }
         *     
         */
        public TypeDescription getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeDescription }
         *     
         */
        public void setDescription(TypeDescription value) {
            this.description = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link TypeItem }
         *     
         */
        public TypeItem getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeItem }
         *     
         */
        public void setItem(TypeItem value) {
            this.item = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public float getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(float value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link Unit }
         *     
         */
        public Unit getUnit() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link Unit }
         *     
         */
        public void setUnit(Unit value) {
            this.unit = value;
        }

        /**
         * Gets the value of the unitPrice property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the value of the unitPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setUnitPrice(Float value) {
            this.unitPrice = value;
        }

        /**
         * Gets the value of the netPrice property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getNetPrice() {
            return netPrice;
        }

        /**
         * Sets the value of the netPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setNetPrice(Float value) {
            this.netPrice = value;
        }

        /**
         * Gets the value of the vat property.
         * 
         * @return
         *     possible object is
         *     {@link VAT }
         *     
         */
        public VAT getVAT() {
            return vat;
        }

        /**
         * Sets the value of the vat property.
         * 
         * @param value
         *     allowed object is
         *     {@link VAT }
         *     
         */
        public void setVAT(VAT value) {
            this.vat = value;
        }

        /**
         * Gets the value of the discountPercentage property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getDiscountPercentage() {
            return discountPercentage;
        }

        /**
         * Sets the value of the discountPercentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setDiscountPercentage(Float value) {
            this.discountPercentage = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the line property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLine() {
            return line;
        }

        /**
         * Sets the value of the line property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLine(BigInteger value) {
            this.line = value;
        }

    }

}
