//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typeSalesOrderDeliveries complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeSalesOrderDeliveries">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Delivery" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="ShippingMethod">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LineItems" type="{}typeSalesOrderDeliveryLineItems" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeSalesOrderDeliveries", propOrder = {
    "delivery"
})
public class TypeSalesOrderDeliveries {

    @XmlElement(name = "Delivery", required = true)
    protected List<TypeSalesOrderDeliveries.Delivery> delivery;

    /**
     * Gets the value of the delivery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delivery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelivery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeSalesOrderDeliveries.Delivery }
     * 
     * 
     */
    public List<TypeSalesOrderDeliveries.Delivery> getDelivery() {
        if (delivery == null) {
            delivery = new ArrayList<TypeSalesOrderDeliveries.Delivery>();
        }
        return this.delivery;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="ShippingMethod">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LineItems" type="{}typeSalesOrderDeliveryLineItems" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "number",
        "deliveryDate",
        "shippingMethod",
        "lineItems"
    })
    public static class Delivery {

        @XmlElement(name = "Number", required = true)
        protected String number;
        @XmlElement(name = "DeliveryDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar deliveryDate;
        @XmlElement(name = "ShippingMethod", required = true)
        protected TypeSalesOrderDeliveries.Delivery.ShippingMethod shippingMethod;
        @XmlElement(name = "LineItems")
        protected TypeSalesOrderDeliveryLineItems lineItems;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumber(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the deliveryDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeliveryDate() {
            return deliveryDate;
        }

        /**
         * Sets the value of the deliveryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeliveryDate(XMLGregorianCalendar value) {
            this.deliveryDate = value;
        }

        /**
         * Gets the value of the shippingMethod property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSalesOrderDeliveries.Delivery.ShippingMethod }
         *     
         */
        public TypeSalesOrderDeliveries.Delivery.ShippingMethod getShippingMethod() {
            return shippingMethod;
        }

        /**
         * Sets the value of the shippingMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSalesOrderDeliveries.Delivery.ShippingMethod }
         *     
         */
        public void setShippingMethod(TypeSalesOrderDeliveries.Delivery.ShippingMethod value) {
            this.shippingMethod = value;
        }

        /**
         * Gets the value of the lineItems property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSalesOrderDeliveryLineItems }
         *     
         */
        public TypeSalesOrderDeliveryLineItems getLineItems() {
            return lineItems;
        }

        /**
         * Sets the value of the lineItems property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSalesOrderDeliveryLineItems }
         *     
         */
        public void setLineItems(TypeSalesOrderDeliveryLineItems value) {
            this.lineItems = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description"
        })
        public static class ShippingMethod {

            @XmlElement(name = "Description", required = true)
            protected Object description;
            @XmlAttribute
            protected String code;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setDescription(Object value) {
                this.description = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

        }

    }

}
