//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeDDMandateTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeDDMandateTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Core"/>
 *     &lt;enumeration value="B2B"/>
 *     &lt;enumeration value="Bottomline"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeDDMandateTypeEnum")
@XmlEnum
public enum TypeDDMandateTypeEnum {

    @XmlEnumValue("Core")
    CORE("Core"),
    @XmlEnumValue("B2B")
    B_2_B("B2B"),
    @XmlEnumValue("Bottomline")
    BOTTOMLINE("Bottomline");
    private final String value;

    TypeDDMandateTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeDDMandateTypeEnum fromValue(String v) {
        for (TypeDDMandateTypeEnum c: TypeDDMandateTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
