//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for typeSalesOrderInvoices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeSalesOrderInvoices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Invoice" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IntegrationForeignKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LineItems" type="{}typeSalesOrderInvoiceLineItems" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="IntegrationCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeSalesOrderInvoices", propOrder = {
    "invoice"
})
public class TypeSalesOrderInvoices {

    @XmlElement(name = "Invoice", required = true)
    protected List<TypeSalesOrderInvoices.Invoice> invoice;
    @XmlAttribute(name = "IntegrationCompanyCode")
    protected String integrationCompanyCode;

    /**
     * Gets the value of the invoice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeSalesOrderInvoices.Invoice }
     * 
     * 
     */
    public List<TypeSalesOrderInvoices.Invoice> getInvoice() {
        if (invoice == null) {
            invoice = new ArrayList<TypeSalesOrderInvoices.Invoice>();
        }
        return this.invoice;
    }

    /**
     * Gets the value of the integrationCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrationCompanyCode() {
        return integrationCompanyCode;
    }

    /**
     * Sets the value of the integrationCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrationCompanyCode(String value) {
        this.integrationCompanyCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IntegrationForeignKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LineItems" type="{}typeSalesOrderInvoiceLineItems" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "number",
        "date",
        "amount",
        "currency",
        "integrationForeignKey",
        "lineItems"
    })
    public static class Invoice {

        @XmlElement(name = "Number", required = true)
        protected BigInteger number;
        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "Amount")
        protected float amount;
        @XmlElement(name = "Currency", required = true)
        protected String currency;
        @XmlElement(name = "IntegrationForeignKey", required = true)
        protected String integrationForeignKey;
        @XmlElement(name = "LineItems")
        protected TypeSalesOrderInvoiceLineItems lineItems;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumber(BigInteger value) {
            this.number = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public float getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(float value) {
            this.amount = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the integrationForeignKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntegrationForeignKey() {
            return integrationForeignKey;
        }

        /**
         * Sets the value of the integrationForeignKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntegrationForeignKey(String value) {
            this.integrationForeignKey = value;
        }

        /**
         * Gets the value of the lineItems property.
         * 
         * @return
         *     possible object is
         *     {@link TypeSalesOrderInvoiceLineItems }
         *     
         */
        public TypeSalesOrderInvoiceLineItems getLineItems() {
            return lineItems;
        }

        /**
         * Sets the value of the lineItems property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeSalesOrderInvoiceLineItems }
         *     
         */
        public void setLineItems(TypeSalesOrderInvoiceLineItems value) {
            this.lineItems = value;
        }

    }

}
