//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Deliveries" type="{}typeSalesOrderDeliveries" minOccurs="0"/>
 *         &lt;element name="Invoices" type="{}typeSalesOrderInvoices" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="salesordernumber" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveries",
    "invoices"
})
@XmlRootElement(name = "WebShopSalesOrder")
public class WebShopSalesOrder {

    @XmlElement(name = "Deliveries")
    protected TypeSalesOrderDeliveries deliveries;
    @XmlElement(name = "Invoices")
    protected TypeSalesOrderInvoices invoices;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String salesordernumber;

    /**
     * Gets the value of the deliveries property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSalesOrderDeliveries }
     *     
     */
    public TypeSalesOrderDeliveries getDeliveries() {
        return deliveries;
    }

    /**
     * Sets the value of the deliveries property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSalesOrderDeliveries }
     *     
     */
    public void setDeliveries(TypeSalesOrderDeliveries value) {
        this.deliveries = value;
    }

    /**
     * Gets the value of the invoices property.
     * 
     * @return
     *     possible object is
     *     {@link TypeSalesOrderInvoices }
     *     
     */
    public TypeSalesOrderInvoices getInvoices() {
        return invoices;
    }

    /**
     * Sets the value of the invoices property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeSalesOrderInvoices }
     *     
     */
    public void setInvoices(TypeSalesOrderInvoices value) {
        this.invoices = value;
    }

    /**
     * Gets the value of the salesordernumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesordernumber() {
        return salesordernumber;
    }

    /**
     * Sets the value of the salesordernumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesordernumber(String value) {
        this.salesordernumber = value;
    }

}
