//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 03:25:32 PM CEST 
//


package nl.sytematic.lib.exactonline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Deliverable"/>
 *         &lt;element ref="{}Activity"/>
 *         &lt;element ref="{}Expense"/>
 *       &lt;/choice>
 *       &lt;attribute name="Project" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliverableOrActivityOrExpense"
})
@XmlRootElement(name = "WorkBreakdownStructure")
public class WorkBreakdownStructure {

    @XmlElements({
        @XmlElement(name = "Expense", type = Expense.class),
        @XmlElement(name = "Activity", type = Activity.class),
        @XmlElement(name = "Deliverable", type = Deliverable.class)
    })
    protected List<Object> deliverableOrActivityOrExpense;
    @XmlAttribute(name = "Project", required = true)
    protected String project;

    /**
     * Gets the value of the deliverableOrActivityOrExpense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliverableOrActivityOrExpense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliverableOrActivityOrExpense().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Expense }
     * {@link Activity }
     * {@link Deliverable }
     * 
     * 
     */
    public List<Object> getDeliverableOrActivityOrExpense() {
        if (deliverableOrActivityOrExpense == null) {
            deliverableOrActivityOrExpense = new ArrayList<Object>();
        }
        return this.deliverableOrActivityOrExpense;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

}
